[package]
authors = ["Jayson Reis <santosdosreis@gmail.com>"]
name = "csv-query-rs"
version = "0.1.0"

[dependencies]
clap = "*"
csv = "*"
error-chain = "*"
rusqlite = "*"

[[bin]]
name = "csv-query"
path = "src/main.rs"
