[package]
authors = ["Jayson Reis <santosdosreis@gmail.com>"]
name = "csv-query-rs"
version = "0.1.0"

[dependencies]
clap = "*"
csv = "*"
error-chain = "*"
# sqlite = "*"

[[bin]]
name = "csv_query"
path = "src/main.rs"

[dependencies.sqlite]
git = "https://github.com/jaysonsantos/sqlite-rs"
branch = "column-name"
